- hosts: localhost
  gather_facts: false
  vars:
    project: "OPTLC-OSPD_Basic-v13.7-bp"
    username: "{{ guid }}"
  vars_prompt:
    - prompt: "GUID for the project?"
      name: guid
      private: no

    - prompt: "USER for the project?"
      name: user
      private: no

    - prompt: "ID for the external network"
      name: external
      private: no

  tasks:
    - set_fact: project_name="{{ project | replace('-bp','') | replace('OPTLC', 'OTLC-LAB-' + user) }}-{{ guid }}"
    - set_fact: userpw="{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"
    - debug: var=userpw

    - command: "date +%s"
      register: date


    - name: Check if project exists
      os_project_facts:
        auth: 
         auth_url: http://169.47.15.163:5000/v3
         project_name: admin
         username: admin
         password: XdmdfJKt4cv9zpyn2Wvdr827b
         user_domain_name: Default
         project_domain_name: Default
        name: "{{ project_name }}"
      register: project_exists

    - fail: msg="Project exists, can't continue"
      when: project_exists.ansible_facts.openstack_projects


    - name: Create project and assign permission
      os_stack:
        auth: 
         auth_url: http://169.47.15.163:5000/v3
         project_name: admin
         username: admin
         password: XdmdfJKt4cv9zpyn2Wvdr827b
         user_domain_name: Default
         project_domain_name: Default
        name: "create-project-{{project_name}}"
        template: "stack_admin.yaml"
        parameters:
          project_name: "{{ project_name }}" 
          project_description: "created:{{ date.stdout }}"
          project_user: "{{ username }}"
          project_userpw: "{{ userpw }}"

    - debug: var=userpw
    - debug: var=username

    - name: auth
      register: objects
      os_auth:
        auth: 
         auth_url: http://169.47.15.163:5000/v3
         project_name: "{{ project_name }}"
         username: "{{ username }}"
         password: "{{ userpw }}"
         user_domain_name: Default
         project_domain_name: Default
 
    - name: Create objects inside the project
      register: objects
      os_stack:
        auth: 
         auth_url: http://169.47.15.163:5000/v3
         project_name: "{{ project_name }}"
         username: "{{ username }}"
         password: "{{ userpw }}"
         user_domain_name: Default
         project_domain_name: Default
        name: "create-objects-{{project_name}}"
        template: "stack_user.yaml"
        parameters:
          public_net_id: "{{ external }}" 
          userdata: ""
    - set_fact: fip="{{ objects.stack.outputs[0].output_value }}"
    - debug: msg="Floating IP {{ fip }} assigned"
    - uri:
       url: https://api.softlayer.com/rest/v3/SoftLayer_Dns_Domain/2800309/createARecord
       user: josegonz
       password: 2c887f0eb0dcc6b2720b488322775fac3b0cf59c77c7364cbff65acaaf307d25 
       method: POST
       body_format: json
       body: {'parameters':["workstation-{{guid}}","{{ fip }}","3600"]}
    - debug: msg="DNS workstation-{{ guid }}.iad.opentlc.com assigned"

