- hosts: localhost
  gather_facts: false
  tasks:
    - name: Rebuild VM
      os_server_action:
        server: "{{ vm }}"
        action: rebuild
        auth: 
         auth_url: http://169.47.15.163:5000/v3
         project_name: admin
         username: admin
         password: XdmdfJKt4cv9zpyn2Wvdr827b
         user_domain_name: Default
         project_domain_name: Default
