# Ravello username and password
export ravelloUser='alberto.gonzalez@redhat.com'
export ravelloPass='Oforte2016$'

# OpenStack username and password
export ospUser='admin'
export ospPass='T4g9fYEfwCuDCwgybCmGq6cxg'

# OpenStack project for user
export ospProject='admin'

# OpenStack keystone URL
export ospAuthURL='http://169.47.188.15:5000'

# Comment this out if you want to use password authentication otherwise it will inject this password into the exporter VM in the root user
#export pubKeyFile="/home/myuser/.ssh/id_rsa.pub"
