- hosts: all
  gather_facts: False
  vars:
    directory: ""
    images:
      
      - ['vdb', '3compute02-sda']  
      
      - ['vdc', '3compute02-CDROM']  
      
      - ['vdd', '0Workstation-boot']  
      
      - ['vde', '1undercloud-vda']  
      
      - ['vdf', 'ipmi-host-boot']  
      
      - ['vdg', 'ipmi-host-repos']  
      
      - ['vdh', 'ipmi-host-registry']  
      
      - ['vdi', '2ctrl01-sda']  
      
      - ['vdj', '2ctrl01-CDROM']  
      
      - ['vdk', '3compute01-sda']  
      
      - ['vdl', '3compute01-CDROM']  
      

  tasks:
    - file:
        path: /root/images/
        state: absent
    - file:
        path: /root/images/
        state: directory
    - yum: name=qemu-img state=present
    - command: qemu-img convert -O qcow2 -p /dev/{{ item[0]}} "/root/images/{{ item[1] }}"
      loop:  "{{ images }}"

    - file:
        path: /home/gpte/images/
        state: absent
      delegate_to: localhost
    - file:
        path: /home/gpte/images/
        state: directory
      delegate_to: localhost

    - fetch:
       src: /root/images/{{ item[1] }}
       dest: /home/gpte/images/{{ item[1] }}
       flat: yes
       validate_checksum: no
      name: "start"
      loop:  "{{ images }}"

    - name: import images 
      delegate_to: localhost
      os_image:
        auth: 
         auth_url: http://169.47.15.163:5000/v3
         project_name: admin
         username: admin
         password: XdmdfJKt4cv9zpyn2Wvdr827b
         user_domain_name: Default
         project_domain_name: Default
        name: "{{ item[1] }}"
        container_format: bare
        disk_format: qcow2
        is_public: True
        filename: "/home/gpte/images/{{ item[1] }}"
      loop:  "{{ images }}"


