- hosts: localhost
  gather_facts: false
  vars:
    project: "OPTLC-OSPD_Basic-v13.7-bp"
  vars_prompt:
    - prompt: "GUID for the project?"
      name: guid
      private: no

    - prompt: "USER for the project?"
      name: user
      private: no


  tasks:
    - set_fact: project_name="{{ project | replace('-bp','') | replace('OPTLC', 'OTLC-LAB-' + user) }}-{{ guid }}"
    - name: Delete objects inside the project
      os_stack:
        auth: 
         auth_url: "{{ auth_url }}"
         project_name: admin
         username: "{{ auth_user }}"
         password: "{{ auth_pass }}"
         user_domain_name: Default
         project_domain_name: Default
        name: "create-objects-{{project_name}}"
        state: absent

    - name: Delete project and unassign permission
      os_stack:
        auth: 
         auth_url: "{{ auth_url }}"
         project_name: admin
         username: "{{ auth_user }}"
         password: "{{ auth_pass }}"
         user_domain_name: Default
         project_domain_name: Default
        name: "create-project-{{project_name}}"
        state: absent
 

