- hosts: localhost
  gather_facts: False
  become: false
  connection: local
  vars:
    heat_repository: git@github.com:redhat-gpe/novello-templates.git
    git_dir: "novello-templates"
    template_dir: "{{ git_dir }}/heat-templates/{{ blueprint_name }}"
    output_dir: "imported/{{ blueprint_name }}-playbooks"
    env_vars:
      outputdir: "{{ output_dir }}"
      bluprint: "{{ blueprint_name }}"
  vars_prompt:
    - prompt: "Name of the BP"
      name: blueprint_name
      private: no

  tasks:
    - name: Debug vars
      debug:
        msg: "Blueprint: {{ blueprint_name }} - Heat Repository: {{ heat_repository }} - Git Dir: {{ git_dir }} - Template dir {{ template_dir }} - output {{ output_dir }}"

    - name: Clone heat-templates repository
      git:
        repo: "{{ heat_repository }}"
        dest: "{{ git_dir}}"
        version: master
        force: true

    - name: Create {{ template_dir }} directory
      file:
        path: "{{ template_dir }}"
        state: directory
        recurse: true

    - name: Copy heat-templates to {{ template_dir }}
      copy:
        src: "{{ item }}"
        dest: "{{ template_dir }}"
      loop:
        - "{{ output_dir }}/stack_admin.yaml"
        - "{{ output_dir }}/stack_user.yaml"
        - "{{ output_dir }}/blueprint.json"
      register: copy_templates

    - name: Add heat templates to git
      shell: cd "{{ git_dir }}" && git add .
      when: copy_templates is changed

    - name: Commit heat templates for {{ blueprint_name }}
      environment:
        GPG_TTY: ""
      shell: cd "{{ git_dir }}" && git commit -m 'Update heat {{ blueprint_name }}'
      when: copy_templates is changed

    - name: Pushing modifications
      shell: cd "{{ git_dir }}" && git push
      when: copy_templates is changed

