---
- hosts: import
  gather_facts: false
  become: false
  vars:
    overwrite_image: True
    output_dir: "/tmp/import/{{ project }}"

  vars_prompt:
    - prompt: "Name of the BP (project)"
      name: project
      private: no

    - prompt: "Image ID (images)"
      name: images
      private: no

  tasks:
    - name: Download images from OpenStack
      environment:
        OS_AUTH_URL: "{{ osp_auth_url }}"
        OS_USERNAME: "{{ osp_auth_username }}"
        OS_PASSWORD: "{{ osp_auth_password }}"
        OS_PROJECT_NAME: "admin"
        OS_PROJECT_DOMAIN_ID: "{{ osp_auth_project_domain }}"
        OS_USER_DOMAIN_NAME: "{{ osp_auth_user_domain }}"
        PATH: "/root/.local/bin:{{ ansible_env.PATH }}"
        CEPH_CONF: "/etc/ceph/{{ ceph_cluster |default('red') }}.conf"
      convert_images:
        ibm_endpoint: "{{ ibm_endpoint }}"
        ibm_auth_endpoint: "{{ ibm_auth_endpoint }}"
        ibm_api_key: "{{ ibm_api_key }}"
        ibm_resource_id: "{{ ibm_resource_id }}"
        bucket: "{{ ibm_bucket_name }}"
        project: "{{ project }}"
        output_dir: "{{ output_dir }}"
        mode: "update"
        images: "{{ images.split() }}"
        glance_pool: "{{ ceph_cluster |default('red') }}-images"
        overwrite: "{{ overwrite_image | default('false') }}"
      register: output
