heat_template_version: 2016-10-14
description: Create a project
parameters:
  userdata:
    type: string
    description: cloud-init for workstation
  public_net_id:
    type: string
    description: The ID for the floating ip
  project_name:
    type: string
    description: Name of the project for the flavors
  guid: 
    type: string
resources:
  Network0_network:
    type: OS::Neutron::Net
    properties:
      name: "Network0"
      shared: false
      #value_specs: {"mtu": 1450}
  Network1_network:
    type: OS::Neutron::Net
    properties:
      name: "Network1"
      shared: false
      #value_specs: {"mtu": 1450}
  Network0_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network0"
      network_id: { get_resource: Network0_network }
      cidr: "192.168.122.0/24"
      gateway_ip: "192.168.122.1"
      enable_dhcp: "True"
      
      allocation_pools: [{"start": 192.168.122.5, "end": 192.168.122.254}]
      
      dns_nameservers:
      
        - 192.168.122.4
      
        - 8.8.8.8
  Network1_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network1"
      network_id: { get_resource: Network1_network }
      cidr: "172.16.0.0/24"
      gateway_ip: ""
      enable_dhcp: "False"
      
      dns_nameservers:
      
        - 192.168.122.4
      
        - 8.8.8.8
  Router0_router:
    type: OS::Neutron::Router
    properties:
      name: "Router0"
      external_gateway_info: { "network": { get_param: public_net_id } }

  
  Router0_Network0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      fixed_ips:
        - ip_address: "192.168.122.1"
  


  
  Router0_Network0_router_if:
    type: OS::Neutron::RouterInterface
    properties:
        router: { get_resource: Router0_router }
        port: { get_resource: Router0_Network0_port }
  
  01workstation_services_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: 01workstation_services_sg
      rules:
      
      - {port_range_max: 22, port_range_min: 22, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      
      - {port_range_max: 443, port_range_min: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 192.168.122.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 192.168.122.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 172.16.0.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 172.16.0.0/255.255.255.0}
      
  03ctrl01-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:00:02:02"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.10"}
      
    
  03ctrl01-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:01:02:02"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.100"}
      
    
  05compute01-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:01:02:05"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.11"}
      
    
  01workstation-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:4b:1d:fb"
      
      security_groups:
        - 01workstation_services_sg
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.2"}
      
    
    depends_on:
      
      
      - 01workstation_services_sg
      
    
  01workstation-0_fip:
    type: OS::Neutron::FloatingIP
    depends_on:
      - 01workstation_server
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: 01workstation-0_port }
  01workstation-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:1c:5d:e9"
      
      security_groups:
        - 01workstation_services_sg
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.21"}
      
    
    depends_on:
      
      
      - 01workstation_services_sg
      
    
  ipmi-host-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:01:02:fd"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.3"}
      
    
  04cfme-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:41:20:f4"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.99"}
      
    
  04cfme-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:5c:e2:90"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.2"}
      
    
  02undercloud-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:00:00:99"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.253"}
      
    
  02undercloud-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:74:c8:fb"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.1"}
      
    
  06compute02-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:01:02:06"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.12"}
      
    
  ipmi-host_volume_REPOS:
    type: OS::Cinder::Volume
    properties:
      name: "ipmi-host-REPOS"
      
      image: "OPTLC-OSP13_Foundations-v0.13-ipmi-host-REPOS"
      
      size: "50"
  ipmi-host_volume_registry:
    type: OS::Cinder::Volume
    properties:
      name: "ipmi-host-registry"
      
      image: "OPTLC-OSP13_Foundations-v0.13-ipmi-host-registry"
      
      size: "100"
  04cfme_volume_data:
    type: OS::Cinder::Volume
    properties:
      name: "04cfme-data"
      
      image: "OPTLC-OSP13_Foundations-v0.13-04cfme-data"
      
      size: "50"
  01workstation_server:
    type: OS::Nova::Server
    properties:
      name: "01workstation"
      
      image: "OPTLC-OSP13_Foundations-v0.13-01workstation-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_1_Memory_8192_Disk_10"]]


      metadata: { "description": "General use RHPDS/OPENTLC Workstation/Bastion Host
guacamole:1"  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: workstation-REPL.rhpds.opentlc.com
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: 01workstation-0_port}
        
        - port: { get_resource: 01workstation-1_port}
        
      
    

  
  02undercloud_server:
    type: OS::Nova::Server
    properties:
      name: "02undercloud"
      
      image: "OPTLC-OSP13_Foundations-v0.13-02undercloud-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_8_Memory_16384_Disk_50"]]


      metadata: { "description": ""  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: undercloud.example.com
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: 02undercloud-0_port}
        
        - port: { get_resource: 02undercloud-1_port}
        
      
    
    depends_on:
      
      - 04cfme
      
      - ipmi-host
      
      - 01workstation
      
    

  
  03ctrl01_server:
    type: OS::Nova::Server
    properties:
      name: "03ctrl01"
      
      image: "OPTLC-OSP13_Foundations-v0.13-03ctrl01-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_2_Memory_16384_Disk_50"]]


      metadata: { "description": "ipmiaddr:192.168.122.201
ipmipw:redhat", "cdrom": "03ctrl01-vol1"  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: ctrl01
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: 03ctrl01-0_port}
        
        - port: { get_resource: 03ctrl01-1_port}
        
      
    
    depends_on:
      
      - 02undercloud
      
    

  
  04cfme_server:
    type: OS::Nova::Server
    properties:
      name: "04cfme"
      
      image: "OPTLC-OSP13_Foundations-v0.13-04cfme-root"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_12288_Disk_20"]]


      metadata: { "description": ""  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: cfme.example.com
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: 04cfme-0_port}
        
        - port: { get_resource: 04cfme-1_port}
        
      
      block_device_mapping_v2:
        
        - volume_id: { get_resource: 04cfme_volume_data }
          boot_index: -1
        
      
    

  
  05compute01_server:
    type: OS::Nova::Server
    properties:
      name: "05compute01"
      
      image: "OPTLC-OSP13_Foundations-v0.13-05compute01-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_16384_Disk_50"]]


      metadata: { "description": "ipmiaddr:192.168.122.202
ipmipw:redhat", "cdrom": "05compute01-vol1"  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: compute01.example.com
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: 05compute01-0_port}
        
      
    
    depends_on:
      
      - 03ctrl01
      
    

  
  06compute02_server:
    type: OS::Nova::Server
    properties:
      name: "06compute02"
      
      image: "OPTLC-OSP13_Foundations-v0.13-06compute02-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_16384_Disk_50"]]


      metadata: { "description": "ipmiaddr:192.168.122.203
ipmipw:redhat", "cdrom": "06compute02-vol1"  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: compute02.example.com
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: 06compute02-0_port}
        
      
    
    depends_on:
      
      - 03ctrl01
      
    

  
  ipmi-host_server:
    type: OS::Nova::Server
    properties:
      name: "ipmi-host"
      
      image: "OPTLC-OSP13_Foundations-v0.13-ipmi-host-boot"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_1_Memory_1024_Disk_20"]]


      metadata: { "description": "Rename this to just ipmi-host for it to work in OPENTLC/RHPDS"  }
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": {get_file: "../99-custom-networking.cfg"}}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: ipmi-host
          
          params:
            REPL: {get_param: guid}
            
      networks:
        
        - port: { get_resource: ipmi-host-0_port}
        
      
      block_device_mapping_v2:
        
        - volume_id: { get_resource: ipmi-host_volume_REPOS }
          boot_index: -1
        
        - volume_id: { get_resource: ipmi-host_volume_registry }
          boot_index: -1
        
      
    

  
  dns_servers:
    type: OS::Heat::Value
    properties:
      type: string
      value:
        list_join:
          - ','
          - 
            - list_join: ['=', ["workstation-REPL.rhpds.opentlc.com", {get_attr: [01workstation-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["workstation.example.com", {get_attr: [01workstation-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["undercloud.example.com", {get_attr: [02undercloud-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["undercloud", {get_attr: [02undercloud-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["compute01.example.com", {get_attr: [05compute01-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["compute01", {get_attr: [05compute01-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["compute02.example.com", {get_attr: [06compute02-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["compute02", {get_attr: [06compute02-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["cfme.example.com", {get_attr: [04cfme-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["cfme", {get_attr: [04cfme-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["classroom", {get_attr: [ipmi-host-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["classroom.example.com", {get_attr: [ipmi-host-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["ipmi-host", {get_attr: [ipmi-host-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["ctrl01", {get_attr: [03ctrl01-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["ctrl01.example.com", {get_attr: [03ctrl01-0_port, fixed_ips, 0, ip_address]} ]]
            
            - list_join: ['=', ["host1.localdomain", {get_attr: [01workstation-0_port, fixed_ips, 0, ip_address]} ]]
            
  dnsserver_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: dnsserver_sg
      rules:
      - {port_range_max: 53, port_range_min: 53, protocol: udp, remote_ip_prefix: "0.0.0.0/0"}

  dnsserver_server:
    type: OS::Nova::Server
    properties:
      name: "internaldns"
      image: "centos7"
      config_drive: True
      flavor: "m1.small"
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/sh
            yum install -y docker
            systemctl enable --now docker
            docker run -dti -p 53:53/tcp -p 53:53/udp -e EXTRA_HOSTS='hosts%'     -t cytopia/bind
          params:
            "hosts%": { get_attr: [dns_servers, value] }
            "REPL": { get_param: guid }
         
      security_groups: [dnsserver_sg]
      networks: 
       - network: { get_resource: Network0_network }
         fixed_ip: 192.168.122.4