- hosts: all
  gather_facts: False
  vars:
    disks:
      
      - ['vdb', '0Workstation-root']  
      
      - ['vdc', '0Workstation-repos']  
      
      - ['vdd', '6Network Node 02-root']  
      
      - ['vde', '1Controller-root']  
      
      - ['vdf', '3Compute Node 01-root']  
      
      - ['vdg', '2Compute Node 00-root']  
      
      - ['vdh', '5Network Node 01-root']  
      
      - ['vdi', '9Storage-root']  
      
      - ['vdj', '4Network Node 00-root']  
      

  tasks:
    - file:
        path: /root/images/
        state: absent
    - file:
        path: /root/images/
        state: directory
    - yum: name=qemu-img state=present
    - command: qemu-img convert -O qcow2 -p /dev/{{ item[0]}} "/root/images/{{ item[1] }}"
      loop:  "{{ disks }}"

    - file:
        path: /root/images/
        state: absent
      delegate_to: localhost
    - file:
        path: /root/images/
        state: directory
      delegate_to: localhost

    - fetch:
       src: /root/images/{{ item[1] }}
       dest: /root/images/{{ item[1] }}
       flat: yes
      loop:  "{{ disks }}"

    - fetch:
        src: /root/images/{{ item[1] }}
        dest: /root/images/{{ item[1] }}
        flat: yes
      loop:  "{{ disks }}"

    - os_image:
        cloud: openstack-project
        name: "{{ item[1] }}"
        container_format: bare
        disk_format: qcow2
        filename: "/root/images/{{ item[1] }}"
      loop:  "{{ disks }}"

      

