heat_template_version: 2016-10-14
description: Create a project
parameters:
  public_net_id:
    type: string
    description: The ID for the floating ip
  project_name:
    type: string
    description: Name of the project for the flavors
  project_guid: 
    type: string
  api_user:
    type: string
    default: ""
    description: User for API calls (i.e. ipmi)
  api_pass:
    type: string
    default: ""
    description: Password for API user
  api_url:
    type: string
    default: ""
    description: OSP URL for API calls
 
resources:
  openstack_project_infra_key:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: $project$-infra_key
          params:
             $project$: { get_param: project_guid }
      save_private_key: true
  Network0_network:
    type: OS::Neutron::Net
    properties:
      name: "Network0"
      shared: false
      value_specs: {"mtu": 1500}
  Network1_network:
    type: OS::Neutron::Net
    properties:
      name: "Network1"
      shared: false
      value_specs: {"mtu": 1500}
  Network0_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network0"
      network_id: { get_resource: Network0_network }
      cidr: "192.168.122.0/24"
      gateway_ip: "192.168.122.1"
      enable_dhcp: "True"
      
      allocation_pools: [{"start": 192.168.122.5, "end": 192.168.122.254}]
      
      dns_nameservers:
      
        - 192.168.122.4
      
        - 8.8.8.8
  Network1_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network1"
      network_id: { get_resource: Network1_network }
      cidr: "172.16.0.0/24"
      gateway_ip: ""
      enable_dhcp: "False"
      
      dns_nameservers:
      
        - 192.168.122.4
      
        - 8.8.8.8
  Router0_router:
    type: OS::Neutron::Router
    properties:
      name: "Router0"
      external_gateway_info: { "network": { get_param: public_net_id } }

  
  Router0_Network0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      fixed_ips:
        - ip_address: "192.168.122.1"
  


  
  Router0_Network0_router_if:
    type: OS::Neutron::RouterInterface
    properties:
        router: { get_resource: Router0_router }
        port: { get_resource: Router0_Network0_port }
  
  01workstation_services_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: 01workstation_services_sg
      rules:
      
      - {port_range_max: 22, port_range_min: 22, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      
      - {port_range_max: 443, port_range_min: 443, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 192.168.122.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 192.168.122.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 172.16.0.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 172.16.0.0/255.255.255.0}
      
  01workstation-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:4b:1d:fb"
      
      security_groups:
        - 01workstation_services_sg
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.2"}
      
    
    depends_on:
      
      
      - 01workstation_services_sg
      
    
  01workstation-0_fip:
    type: OS::Neutron::FloatingIP
    depends_on:
      - 01workstation_server
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: 01workstation-0_port }
  01workstation-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:1c:5d:e9"
      
      security_groups:
        - 01workstation_services_sg
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.21"}
      
    
    depends_on:
      
      
      - 01workstation_services_sg
      
    
  06compute02-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:01:02:06"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.12"}
      
    
  05compute01-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:01:02:05"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.11"}
      
    
  03ctrl01-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:00:02:02"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.10"}
      
    
  03ctrl01-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:01:02:02"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.100"}
      
    
  ipmi-host-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:01:02:fd"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.3"}
      
    
  02undercloud-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:00:00:99"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "192.168.122.253"}
      
    
  02undercloud-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:74:c8:fb"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "172.16.0.1"}
      
    
  ipmi-host_volume_REPOS:
    type: OS::Cinder::Volume
    properties:
      name: "ipmi-host-REPOS"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-ipmi-host-REPOS"
      
      size: "50"
  ipmi-host_volume_registry:
    type: OS::Cinder::Volume
    properties:
      name: "ipmi-host-registry"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-ipmi-host-registry"
      
      size: "100"
  01workstation_server:
    type: OS::Nova::Server
    properties:
      name: "01workstation"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-01workstation-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_1_Memory_2048_Disk_10"]]

      
      key_name:  { get_resource: openstack_project_infra_key }
      
      metadata: 
        "description": "General use RHPDS/OPENTLC Workstation/Bastion Host
guacamole:1"
        "public_dns": "workstation-REPL.rhpds.opentlc.com"
         
        
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: workstation-REPL.rhpds.opentlc.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: 01workstation-0_port}
        
        - port: { get_resource: 01workstation-1_port}
        
      
    

  
  02undercloud_server:
    type: OS::Nova::Server
    properties:
      name: "02undercloud"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-02undercloud-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_8_Memory_16384_Disk_50"]]

      
      metadata: 
        "description": ""
        "public_dns": ""
         
        
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: undercloud.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: 02undercloud-0_port}
        
        - port: { get_resource: 02undercloud-1_port}
        
      
    

  
  03ctrl01_server:
    type: OS::Nova::Server
    properties:
      name: "03ctrl01"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-03ctrl01-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_2_Memory_16384_Disk_50"]]

      
      metadata: 
        "description": "ipmiaddr:192.168.122.201
ipmipw:redhat"
        "public_dns": ""
         
        "cdrom": "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-03ctrl01-vol1"
         
        
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: ctrl01
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: 03ctrl01-0_port}
        
        - port: { get_resource: 03ctrl01-1_port}
        
      
    

  
  05compute01_server:
    type: OS::Nova::Server
    properties:
      name: "05compute01"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-05compute01-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_16_Memory_65536_Disk_50"]]

      
      metadata: 
        "description": "ipmiaddr:192.168.122.202
ipmipw:redhat"
        "public_dns": ""
         
        "cdrom": "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-05compute01-vol1"
         
        
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: compute01.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: 05compute01-0_port}
        
      
    

  
  06compute02_server:
    type: OS::Nova::Server
    properties:
      name: "06compute02"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-06compute02-vol"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_16_Memory_65536_Disk_50"]]

      
      metadata: 
        "description": "ipmiaddr:192.168.122.203
ipmipw:redhat"
        "public_dns": ""
         
        "cdrom": "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-06compute02-vol1"
         
        
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: compute02.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: 06compute02-0_port}
        
      
    

  
  ipmi-host_server:
    type: OS::Nova::Server
    properties:
      name: "ipmi-host"
      
      image: "OPTLC-RHTE2019-OCP4.2_OSP13-bp-red-ipmi-host-boot"
      
      config_drive: True
      flavor:
         list_join: ['-', [{ get_param: project_name }, "CPU_1_Memory_1024_Disk_20"]]

      
      metadata: 
        "description": "Rename this to just ipmi-host for it to work in OPENTLC/RHPDS"
        "public_dns": ""
         
        
      personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: ipmi-host
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: ipmi-host-0_port}
        
      
      block_device_mapping_v2:
        
        - volume_id: { get_resource: ipmi-host_volume_REPOS }
          boot_index: -1
        
        - volume_id: { get_resource: ipmi-host_volume_registry }
          boot_index: -1
        
      
    

  
  dns_servers:
    type: OS::Heat::Value
    properties:
      type: string
      value:
        list_join:
          - "\n"
          - 
            - list_join: [' ', [{get_attr: [01workstation-0_port, fixed_ips, 0, ip_address]}, "workstation-REPL.rhpds.opentlc.com" ]]
            
            - list_join: [' ', [{get_attr: [01workstation-0_port, fixed_ips, 0, ip_address]}, "workstation.example.com" ]]
            
            - list_join: [' ', [{get_attr: [02undercloud-0_port, fixed_ips, 0, ip_address]}, "undercloud.example.com" ]]
            
            - list_join: [' ', [{get_attr: [02undercloud-0_port, fixed_ips, 0, ip_address]}, "undercloud" ]]
            
            - list_join: [' ', [{get_attr: [05compute01-0_port, fixed_ips, 0, ip_address]}, "compute01.example.com" ]]
            
            - list_join: [' ', [{get_attr: [05compute01-0_port, fixed_ips, 0, ip_address]}, "compute01" ]]
            
            - list_join: [' ', [{get_attr: [06compute02-0_port, fixed_ips, 0, ip_address]}, "compute02.example.com" ]]
            
            - list_join: [' ', [{get_attr: [06compute02-0_port, fixed_ips, 0, ip_address]}, "compute02" ]]
            
            - list_join: [' ', [{get_attr: [ipmi-host-0_port, fixed_ips, 0, ip_address]}, "classroom" ]]
            
            - list_join: [' ', [{get_attr: [ipmi-host-0_port, fixed_ips, 0, ip_address]}, "classroom.example.com" ]]
            
            - list_join: [' ', [{get_attr: [ipmi-host-0_port, fixed_ips, 0, ip_address]}, "ipmi-host" ]]
            
            - list_join: [' ', [{get_attr: [03ctrl01-0_port, fixed_ips, 0, ip_address]}, "ctrl01" ]]
            
            - list_join: [' ', [{get_attr: [03ctrl01-0_port, fixed_ips, 0, ip_address]}, "ctrl01.example.com" ]]
            
            - list_join: [' ', [{get_attr: [01workstation-0_port, fixed_ips, 0, ip_address]}, "host1.localdomain" ]]
            
  dnsserver_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: dnsserver_sg
      rules:
      - {port_range_max: 53, port_range_min: 53, protocol: udp, remote_ip_prefix: "0.0.0.0/0"}

  dnsserver_server:
    type: OS::Nova::Server
    depends_on:
      - dnsserver_sg
    properties:
      name: "internaldns"
      image: "centos7"
      config_drive: True
      flavor: "m1.small"
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/sh
            echo "Start123" | passwd --stdin root
            echo nameserver 8.8.8.8 > /etc/resolv.conf
            echo "$hosts$" >> /etc/hosts
            sed -i "s/REPL/$GUID$/" /etc/hosts
            yum install -y dnsmasq
            systemctl enable --now dnsmasq
          params:
            "$hosts$": { get_attr: [dns_servers, value] }
            "$GUID$": { get_param: project_guid }
         
      security_groups: [dnsserver_sg]
      networks: 
       - network: { get_resource: Network0_network }
         fixed_ip: 192.168.122.4
outputs:
  openstack_project_infra_key:
    description: The SSH infra key
    value: {get_attr: [openstack_project_infra_key, private_key]}

  01workstation-0_fip:
    description: FIP for 01workstation-0
    value: {get_attr: [01workstation-0_fip, floating_ip_address ]} 


